
name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Pytest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.11.2
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.2
    - name: Install Dependencies
      run: |
        pip install poetry
        poetry install
    - name: mypy
      run: |
        poetry run pytest mypy robotpy_toolkit_7407/